/*
 * This file is generated by jOOQ.
 */
package org.record.month_orient.infrastructure.repository.mysql.monthorient;


import java.io.Serializable;
import java.util.LinkedHashMap;


/**
 * This class is generated by cloud.jooq.
 */
public class MonthOrientContentObject  implements Serializable {

    private static final long serialVersionUID = 1L;

    public String id;
    public String parentId;
    public String  userId;
    public String  userName;
    public String  monthOrientRunId;
    public String  content;
    public String  type;
    public Long    lastModified;
    public Integer index;

    public MonthOrientContentObject()
    {
    }


    public LinkedHashMap<String, Object> toMap() {
        LinkedHashMap<String,Object> map = new LinkedHashMap<>();
        map.put("id",id);
        map.put("parentId",parentId);
        map.put("userId",userId);
        map.put("userName",userName);
        map.put("monthOrientRunId",monthOrientRunId);
        map.put("content",content);
        map.put("type",type);
        map.put("lastModified",lastModified);
        map.put("index",index);
        return map;
    }

}
